### ISSUE TITLE
switching to javafx-gradle-plugin from FibreFox

### ISSUE THREAD

**Issue by cyc1ingsir** [Kairos-Project/kairos-example#2]
As shemnon states here:
https://bitbucket.org/shemnon/javafx-gradle/issues/49/documentation-and-a-working-sample
(see entry from March 2nd) he is no longer maintaining the plugin.
FibreFox the maintainer of the javafx-maven-plugin seems to have stepped in and taken over:
https://github.com/FibreFoX/javafx-gradle-plugin
(see here too: 
- http://stackoverflow.com/a/35408831/2664521 
- http://stackoverflow.com/questions/35098495/is-javafx-gradle-plugin-secure-to-use
  )
  May I suggest to switch over to the FibreFox's gradle-plugin?

**Comment by marconi1992** [comment]
Hello @cyc1ingsir, thanks for the advice, I'll  work in that.
